language: php

php:
  - 7.3

env:
  matrix:
    - PREFER_LOWEST="--prefer-lowest"
    - PREFER_LOWEST=""

install:
  - composer update --prefer-source $PREFER_LOWEST

script:
  - find lib/ -type f -name '*.php' -print0 | xargs -0 -L1 -P4 -- php -l
  - vendor/bin/phpunit
  - vendor/bin/phpstan analyse
