language: php

php:
  - 7.3
  - 7.4

env:
  matrix:
    - PREFER_LOWEST="--prefer-lowest"
    - PREFER_LOWEST=""

install:
  - composer validate --strict
  - composer update --prefer-source $PREFER_LOWEST

script:
  - find lib/ -type f -name '*.php' -print0 | xargs -0 -L1 -P4 -- php -l
  - vendor/bin/php-cs-fixer --no-interaction --dry-run --diff -v fix lib/
  - vendor/bin/phpstan analyse
  - vendor/bin/phpunit
  
